// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contacts.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Specifies how to parse contacts
type ContactType int32

const (
	ContactType_PHONE ContactType = 0
	ContactType_EMAIL ContactType = 1
)

var ContactType_name = map[int32]string{
	0: "PHONE",
	1: "EMAIL",
}

var ContactType_value = map[string]int32{
	"PHONE": 0,
	"EMAIL": 1,
}

func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}

func (ContactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_72e48e1bf84d56b8, []int{0}
}

// Contains the raw contact information along with parsing hints
type Contact struct {
	Type                 ContactType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.ContactType" json:"type,omitempty"`
	Contact              string      `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e48e1bf84d56b8, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetType() ContactType {
	if m != nil {
		return m.Type
	}
	return ContactType_PHONE
}

func (m *Contact) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.ContactType", ContactType_name, ContactType_value)
	proto.RegisterType((*Contact)(nil), "pb.Contact")
}

func init() { proto.RegisterFile("contacts.proto", fileDescriptor_72e48e1bf84d56b8) }

var fileDescriptor_72e48e1bf84d56b8 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x2b,
	0x49, 0x4c, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2,
	0xe0, 0x62, 0x77, 0x86, 0x88, 0x0a, 0x29, 0x73, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0xf0, 0x19, 0xf1, 0xeb, 0x15, 0x24, 0xe9, 0x41, 0xa5, 0x42, 0x2a, 0x0b, 0x52, 0x83,
	0xc0, 0x92, 0x42, 0x12, 0x5c, 0xec, 0x50, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x60,
	0x5c, 0x2d, 0x65, 0x2e, 0x6e, 0x24, 0xe5, 0x42, 0x9c, 0x5c, 0xac, 0x01, 0x1e, 0xfe, 0x7e, 0xae,
	0x02, 0x0c, 0x20, 0xa6, 0xab, 0xaf, 0xa3, 0xa7, 0x8f, 0x00, 0x63, 0x12, 0x1b, 0xd8, 0x66, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x9b, 0x12, 0x19, 0x8b, 0x00, 0x00, 0x00,
}
