// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Status messages send generic meta information about the state of the inbox.
type Status struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

// Message objects represent a single, encrypted message sent from one inbox to another.
type Message struct {
	From                 string               `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 []byte               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// Messages are the primary serialization format for sending multiple message objects
// between Rossby replicas and to and from clients. They are simply a wrapper for one
// or more messages and status meta information.
type Messages struct {
	Status               *Status    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "pb.Status")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Messages)(nil), "pb.Messages")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x6a, 0xc4, 0x20,
	0x10, 0x86, 0xd1, 0x5d, 0xd2, 0xec, 0x58, 0xf6, 0xe0, 0x49, 0xf6, 0x52, 0xf1, 0x52, 0x4f, 0x06,
	0xd2, 0x4b, 0x5f, 0xa2, 0x17, 0x5b, 0xe8, 0x39, 0x52, 0x13, 0x0a, 0x95, 0x91, 0x68, 0x0e, 0xa5,
	0x2f, 0x5f, 0xa2, 0x49, 0xf6, 0x36, 0xcc, 0xfc, 0x7c, 0xdf, 0x3f, 0x70, 0x0d, 0x3e, 0xa5, 0x61,
	0xf2, 0xc9, 0xc4, 0x19, 0x33, 0x72, 0x1a, 0xdd, 0xed, 0x69, 0x42, 0x9c, 0x7e, 0x7c, 0x57, 0x36,
	0x6e, 0x19, 0xbb, 0xfc, 0x1d, 0x7c, 0xca, 0x43, 0x88, 0x35, 0xa4, 0x5a, 0x68, 0xde, 0xf3, 0x90,
	0x97, 0xa4, 0xfe, 0xe0, 0xe1, 0xad, 0x02, 0x38, 0x87, 0xf3, 0x38, 0x63, 0x10, 0x44, 0x12, 0x7d,
	0xb1, 0x65, 0xe6, 0x57, 0xa0, 0x19, 0x05, 0x2d, 0x1b, 0x9a, 0x91, 0xbf, 0xc2, 0xe5, 0x60, 0x89,
	0x93, 0x24, 0x9a, 0xf5, 0x37, 0x53, 0x6d, 0x66, 0xb7, 0x99, 0x8f, 0x3d, 0x61, 0xef, 0xe1, 0x95,
	0xee, 0xf0, 0xeb, 0x57, 0x9c, 0x25, 0xd1, 0x8f, 0xb6, 0xcc, 0xea, 0x13, 0xda, 0x4d, 0x9e, 0xb8,
	0x82, 0x26, 0x95, 0x4a, 0xc5, 0xcf, 0x7a, 0x30, 0xd1, 0x99, 0x5a, 0xd2, 0x6e, 0x17, 0xfe, 0x0c,
	0xed, 0xfe, 0xad, 0xa0, 0xf2, 0xa4, 0x59, 0xcf, 0xd6, 0xd4, 0xc6, 0xb0, 0xc7, 0xd1, 0x35, 0xa5,
	0xcb, 0xcb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xee, 0x62, 0x1f, 0x1d, 0x01, 0x00, 0x00,
}
