// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Profile objects store information about the state of a single inbox (e.g. user) and
// is the primary data object that is read and written to in most API calls. Although
// the profile is not generally sent over the network, it is serialized using protocol
// buffers to store in the database.
type Profile struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contacts             []*Contact           `protobuf:"bytes,2,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Devices              []*Device            `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	Joined               *timestamp.Timestamp `protobuf:"bytes,14,opt,name=joined,proto3" json:"joined,omitempty"`
	LastSeen             *timestamp.Timestamp `protobuf:"bytes,15,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Profile) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Profile) GetJoined() *timestamp.Timestamp {
	if m != nil {
		return m.Joined
	}
	return nil
}

func (m *Profile) GetLastSeen() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeen
	}
	return nil
}

// Users can send and receive messages from multiple devices (e.g. their phone or their
// laptop). Devices are authorized to send and receive messages by the application and
// per-device tokens are the primary form of authentication. Devices can also be
// "deauthorized" so that they can no longer send or receive messages on behalf of a
// user, but without canceling that user's entire account.
type Device struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authorized           bool                 `protobuf:"varint,2,opt,name=authorized,proto3" json:"authorized,omitempty"`
	Cursor               uint64               `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Token                string               `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,13,opt,name=created,proto3" json:"created,omitempty"`
	LastAuth             *timestamp.Timestamp `protobuf:"bytes,14,opt,name=last_auth,json=lastAuth,proto3" json:"last_auth,omitempty"`
	LastSync             *timestamp.Timestamp `protobuf:"bytes,15,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetAuthorized() bool {
	if m != nil {
		return m.Authorized
	}
	return false
}

func (m *Device) GetCursor() uint64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *Device) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Device) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Device) GetLastAuth() *timestamp.Timestamp {
	if m != nil {
		return m.LastAuth
	}
	return nil
}

func (m *Device) GetLastSync() *timestamp.Timestamp {
	if m != nil {
		return m.LastSync
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "pb.Profile")
	proto.RegisterType((*Device)(nil), "pb.Device")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x69, 0x37, 0xbb, 0xed, 0x8c, 0x4d, 0x08, 0x22, 0x61, 0x17, 0x5a, 0x86, 0x60, 0xaf,
	0x3a, 0x98, 0x82, 0xd7, 0xa2, 0x0f, 0x20, 0xd1, 0x7b, 0x69, 0x93, 0xb3, 0x2d, 0xba, 0x25, 0x25,
	0x49, 0x85, 0xf9, 0x10, 0xbe, 0x9d, 0xef, 0x23, 0x4d, 0xd6, 0x29, 0x78, 0xb1, 0x5d, 0x9e, 0xff,
	0x7c, 0x39, 0xf9, 0xff, 0x1f, 0x46, 0x95, 0xd1, 0x0b, 0xb9, 0xc6, 0xbc, 0x32, 0xda, 0x69, 0x12,
	0x57, 0xe5, 0x64, 0xcc, 0xb5, 0x72, 0x05, 0x77, 0x36, 0x68, 0x93, 0xcb, 0xa5, 0xd6, 0xcb, 0x35,
	0xce, 0xfc, 0x54, 0xd6, 0x8b, 0x99, 0x93, 0x1b, 0xb4, 0xae, 0xd8, 0x54, 0x01, 0x98, 0x7e, 0x47,
	0xd0, 0x7b, 0x0a, 0x67, 0xc8, 0x18, 0x62, 0x29, 0x68, 0x94, 0x46, 0xd9, 0x80, 0xc5, 0x52, 0x90,
	0x6b, 0xe8, 0xb7, 0xe7, 0x68, 0x9c, 0x76, 0xb2, 0xe1, 0x7c, 0x98, 0x57, 0x65, 0xfe, 0x10, 0x34,
	0xb6, 0x5f, 0x92, 0x2b, 0xe8, 0x09, 0xfc, 0x90, 0x1c, 0x2d, 0xed, 0x78, 0x0e, 0x1a, 0xee, 0xd1,
	0x4b, 0xac, 0x5d, 0x91, 0x39, 0x24, 0x6f, 0x5a, 0x2a, 0x14, 0x74, 0x9c, 0x46, 0xd9, 0x70, 0x3e,
	0xc9, 0x83, 0xb9, 0xbc, 0x35, 0x97, 0xbf, 0xb4, 0xe6, 0xd8, 0x8e, 0x24, 0x77, 0x30, 0x58, 0x17,
	0xd6, 0xbd, 0x5a, 0x44, 0x45, 0x4f, 0x0f, 0x3e, 0xeb, 0x37, 0xf0, 0x33, 0xa2, 0x9a, 0x7e, 0xc5,
	0x90, 0x04, 0x03, 0xff, 0x62, 0x5d, 0x00, 0x14, 0xb5, 0x5b, 0x69, 0x23, 0x3f, 0x51, 0xd0, 0x38,
	0x8d, 0xb2, 0x3e, 0xfb, 0xa3, 0x90, 0x73, 0x48, 0x78, 0x6d, 0xac, 0x36, 0xb4, 0x93, 0x46, 0x59,
	0x97, 0xed, 0x26, 0x72, 0x06, 0x27, 0x4e, 0xbf, 0xa3, 0xa2, 0x5d, 0x7f, 0x2a, 0x0c, 0xe4, 0x16,
	0x7a, 0xdc, 0x60, 0xe1, 0x50, 0xd0, 0xd1, 0x41, 0x7f, 0x2d, 0xba, 0xcf, 0xd5, 0x7c, 0x7b, 0x44,
	0x1d, 0x3e, 0xd7, 0x7d, 0xed, 0x56, 0xbf, 0x85, 0x6c, 0x15, 0x3f, 0xba, 0x90, 0xad, 0xe2, 0x65,
	0xe2, 0xb7, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xb6, 0x45, 0x37, 0x35, 0x02, 0x00,
	0x00,
}
